---
- name: Default Ubuntu
  hosts: localhost
  vars:
    primary_user: "tgoshinski"
    buntu_ver: "24.04"
    buntu_name: "noble"
    dropbox_ver: "2024.04.17" # https://linux.dropboxstatic.com/packages/ubuntu/
    go_ver: "1.23.5"          # https://go.dev/dl/
    jdk_lts: "21"             # https://openjdk.org/projects/jdk/
    node_edge: "23"           # https://nodejs.org/en
    slack_ver: "4.41.105"     # https://slack.com/downloads/linux
    toolbox_ver: "2.5.2.35332"
    source_key: "./.ssh_vault/config"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/config"
    bb_source_key: "./.ssh_vault/bitbucket/id_rsa"
    bb_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/bitbucket/id_rsa"
    gh_source_key: "./.ssh_vault/github/id_rsa"
    gh_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/github/id_rsa"
  pre_tasks:
    - name: Update Package Manager
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - name: Get SSH Keys
      ansible.builtin.import_tasks: tasks/ssh.yml

    - name: Install Core Packages
      ansible.builtin.import_tasks: tasks/core.yml

    - name: GitHub CLI
      ansible.builtin.import_tasks: tasks/github-cli.yml

    - name: Additional Fonts
      ansible.builtin.import_tasks: tasks/fonts.yml

    - name: Go
      ansible.builtin.import_tasks: tasks/golang.yml

    - name: ZSH
      ansible.builtin.import_tasks: tasks/zsh.yml

    - name: Vim and Plugins
      ansible.builtin.import_tasks: tasks/vim.yml

    # - name: NeoVim and Plugins
    #   ansible.builtin.import_tasks: tasks/nvim.yml

    - name: Node / Volta / Deno
      ansible.builtin.import_tasks: tasks/node.yml

    - name: Flutter
      ansible.builtin.import_tasks: tasks/flutter.yml

    - name: Rust / Cargo
      ansible.builtin.import_tasks: tasks/rust.yml

    - name: Ruby
      ansible.builtin.import_tasks: tasks/ruby.yml

    ##  As of right now, Ubuntu is current with Java LTS
    # - name: Java JDK
    #   ansible.builtin.import_tasks: tasks/java.yml

    - name: Python Version Manager
      ansible.builtin.import_tasks: tasks/python.yml

    - name: TMUX Terminal Multiplexer
      ansible.builtin.import_tasks: tasks/tmux.yml

    - name: My Dotfiles (.vimrc, .zshrc, etc.)
      ansible.builtin.import_tasks: tasks/dotfiles.yml

    - name: .NET and such
      ansible.builtin.import_tasks: tasks/microsoft.yml

    - name: Chrome Browser
      ansible.builtin.import_tasks: tasks/chrome.yml

    - name: Edge Browser
      ansible.builtin.import_tasks: tasks/edge.yml

    - name: Firefox Browser
      ansible.builtin.import_tasks: tasks/firefox.yml

    - name: Docker
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: LibreOffice Suite
      ansible.builtin.import_tasks: tasks/libreoffice.yml

    - name: JetBrains Toolbox
      ansible.builtin.import_tasks: tasks/toolbox.yml

    - name: Slack
      ansible.builtin.import_tasks: tasks/slack.yml

    - name: DropBox, Gimp, Inkscape, etc.
      ansible.builtin.import_tasks: tasks/productivity.yml

    - name: Post install script and instructions
      ansible.builtin.import_tasks: tasks/statics.yml

    # - name: LaTeX packages and editor (takes a long time)
    #   ## TexLive is enormous - moving this to the end to be abortable
    #   ansible.builtin.import_tasks: tasks/latex.yml
