- name: chrome | Download Google Chrome .deb package
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
  tags:
    - install
    - browser
    - chrome

- name: chrome | Install Google Chrome .deb package
  become: true
  ansible.builtin.apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
  tags:
    - install
    - browser
    - chrome
