- name: Install Google Chrome Browser
  become: true
  shell: >
    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
    && apt update
    && apt install google-chrome-stable
  tags:
    - install
    - browser
    - chrome
