- name: Download Google Chrome .deb package
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
  tags:
    - install
    - browser
    - chrome

- name: Install Google Chrome .deb package
  become: true
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
  tags:
    - install
    - browser
    - chrome
