- name: Install System Packages 1
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev", "xz-utils"]
  tags:
    - install
    - core

- name: Install System Packages 2
  become: true
  apt:
    name: [ "unzip", "libtool", "libtool-bin", "gettext", "fonts-powerline", "fonts-firacode", "tree" ]
  tags:
    - install
    - core

- name: Install System Packages 3
  become: true
  apt:
    name: [ "curl", "htop", "lsof", "python3-pip", "pavucontrol", "moreutils", "gnupg2", "zip", "lib32ncurses6", "lib32stdc++6" ]
  tags:
    - install
    - core
