---
- name: core | Install System Packages 1
  become: true
  ansible.builtin.apt:
    name: [
      "apt-transport-https",
      "build-essential",
      "cmake",
      "gnutls-bin",
      "libpthread-stubs0-dev",
      "locales",
      "parallel",
      "pkg-config",
      "xz-utils"
    ]
  tags:
    - install
    - core

- name: core | Install System Packages 2
  become: true
  ansible.builtin.apt:
    name: [
      "ca-certificates",
      "gettext",
      "libtool",
      "libtool-bin",
      "tree",
      "unzip"
    ]
  tags:
    - install
    - core

- name: core | Install System Packages 3
  become: true
  ansible.builtin.apt:
    name: [
      "curl",
      "fzf",
      "gnupg",
      "htop",
      "lsof",
      "python3-pip",
      "pavucontrol",
      "moreutils",
      "gnupg2",
      "zip",
      "lib32ncurses6",
      "lib32stdc++6",
      "libdb-dev",
      "libgdbm-dev",
      "libffi-dev",
      "libgmp-dev",
      "libncurses5-dev",
      "libreadline6-dev",
      "libssl-dev",
      "libyaml-dev",
      "python3-gpg",
      "python3-levenshtein",
      "python3-rapidfuzz",
      "python3-websocket",
      "uuid-dev",
      "wget"
    ]
  tags:
    - install
    - core

- name: core | Ensure a local bin directory
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.local/bin"
    mode: "0755"
    state: directory
  tags:
    - install
    - core
