- name: Docker Desktop Pre-req(s)
  become: true
  apt:
    name: [
      "gnome-terminal"
    ]
  tags:
    - install
    - docker

- name: Add Docker repository
  become: true
  shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
    && chmod a+r /etc/apt/trusted.gpg.d/docker.gpg
    && echo "deb [arch="$(dpkg --print-architecture)"] https://download.docker.com/linux/ubuntu {{ buntuname }} stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
    - install
    - docker

- name: Install Docker Engine
  become: true
  apt:
    update_cache: true
    name: [
      "docker-ce",
      "docker-ce-cli",
      "containerd.io",
      "docker-buildx-plugin",
      "docker-compose-plugin"
    ]
  tags:
    - install
    - docker

- name: Add Primary User to Docker Group
  become: true
  shell: usermod -aG docker {{ primaryuser }}
  tags:
    - install
    - docker
