- name: Docker Desktop Pre-req(s)
  become: true
  apt:
    name: [
      "gnome-terminal"
    ]
  tags:
    - install
    - docker

- name: Download Docker Desktop .deb
  get_url:
    url: https://desktop.docker.com/linux/main/amd64/docker-desktop-{{ dockerver }}-amd64.deb
    dest: /tmp/docker-desktop.deb
  tags:
    - install
    - docker

- name: Install Docker Desktop .deb package
  become: true
  apt:
    deb: /tmp/docker-desktop.deb
  tags:
    - install
    - docker

- name: Add Primary User to Docker Group
  become: true
  shell: usermod -aG docker {{ primaryuser }}
  tags:
    - install
    - docker
