- name: Setup Docker Community Edition Repository
  become: true
  shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    && apt-cache policy docker-ce
  tags:
    - install
    - docker

- name: Install Dcoker Community Edition
  become: true
  apt:
    update_cache: yes
    name: docker-ce
  tags:
    - install
    - docker-ce

- name: Add Primary User to Docker Group
  become: true
  shell: usermod -aG docker tgoshinski
  tags:
    - install
    - docker
