---
- name: docker | Docker Desktop prerequisites
  become: true
  ansible.builtin.apt:
    name: "gnome-terminal"
  tags:
    - install
    - docker

- name: docker | Add Docker repository
  become: true
  ansible.builtin.shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
    && chmod a+r /etc/apt/trusted.gpg.d/docker.gpg
    && echo "deb [arch="$(dpkg --print-architecture)"] https://download.docker.com/linux/ubuntu {{ buntu_name }} stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
    - install
    - docker

- name: docker | Install Docker Engine
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: [
      "docker-ce",
      "docker-ce-cli",
      "containerd.io",
      "docker-buildx-plugin",
      "docker-compose-plugin"
    ]
  tags:
    - install
    - docker

- name: docker | Add Primary User to Docker Group
  become: true
  user:
    name: "{{ primary_user }}"
    append: true
    groups: docker
  tags:
    - install
    - docker
