---
- name: dotfiles | Cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:code-chimp/dotfiles.library.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles.library"
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags:
    - install
    - dotfiles

- name: dotfiles | Stow dotfiles
  ansible.builtin.shell: cd $HOME/.dotfiles.library && ./restore.sh
  tags:
    - install
    - dotfiles
