---
- name: dotfiles | Cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:code-chimp/dotfiles.library.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles.library"
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags:
    - install
    - dotfiles

- name: dotfiles | Restore dotfiles
  ansible.builtin.shell: >
    chmod 0755 $HOME/.dotfiles.library/restore.sh
    && $HOME/.dotfiles.library/restore.sh
  tags:
    - install
    - dotfiles
