- name: firefox | Firefox PPA (ppa:mozillateam/ppa)
  become: true
  ansible.builtin.shell: apt-add-repository -y ppa:mozillateam/ppa
  tags:
    - install
    - browser
    - firefox

- name: firefox | Install Firefox
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: firefox
    state: latest
  tags:
    - install
    - browser
    - firefox
