- name: Firefox PPA (ppa:mozillateam/ppa)
  become: true
  apt_repository:
    repo: ppa:mozillateam/ppa
    state: present
    update_cache: True
  tags:
    - install
    - browser
    - firefox

- name: Install Firefox
  become: true
  apt:
    name: firefox
    state: latest
  tags:
    - install
    - browser
    - firefox
