- name: Firefox Developer PPA (ppa:ubuntu-mozilla-daily/firefox-aurora)
  become: true
  apt_repository:
    repo: ppa:ubuntu-mozilla-daily/firefox-aurora
    state: present
    update_cache: True
  tags:
    - install
    - browser
    - firefox

- name: Install Firefox Developer Edition
  become: true
  apt:
    name: firefox
    state: latest
  tags:
    - install
    - browser
    - firefox
