---
- name: flutter | Install Flutter Dependencies
  become: true
  ansible.builtin.apt:
    name: [
      "clang",
      "libglu1-mesa",
      "libgtk-3-dev",
      "ninja-build"
    ]
    state: latest
  tags:
    - install
    - flutter

- name: flutter | Clone Flutter
  ansible.builtin.git:
    repo: 'https://github.com/flutter/flutter.git'
    dest: "{{ lookup('env', 'HOME') }}/flutter"
  tags:
    - install
    - flutter
