---
- name: flutter | Install Flutter Dependencies
  become: true
  ansible.builtin.apt:
    name: libglu1-mesa
    state: latest
  tags:
    - install
    - flutter

- name: flutter | Clone Flutter
  ansible.builtin.git:
    repo: 'https://github.com/flutter/flutter.git'
    dest: "{{ lookup('env', 'HOME') }}/flutter"
  tags:
    - install
    - flutter
