- name: add git email
  git_config:
    name: user.email
    scope: global
    value: "tim@code-chimp.com"
  tags:
  - git

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Tim Goshinski"
  tags:
  - git
