- name: latex | TeXstudio PPA (ppa:sunderme/texstudio)
  become: true
  ansible.builtin.shell: apt-add-repository -y ppa:sunderme/texstudio
  tags:
    - install
    - latex

- name: latex | Install TeXstudio
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: [
      "texstudio"
    ]
  tags:
    - install
    - latex

- name: latex | Install LaTeX Dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: [
      "asymptote",
      "asymptote-doc",
      "ghostscript",
      "ghostscript-x",
      "biber",
      "dvipng",
      "latexdiff",
      "latexmk",
      "okular"
    ]
  tags:
    - install
    - latex

- name: latex | Install Giant TexLive metapackage
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: [
      "texlive-full"
    ]
  tags:
    - install
    - latex
