- name: TeXstudio PPA (ppa:sunderme/texstudio)
  become: true
  apt_repository:
   repo: ppa:sunderme/texstudio
   state: present
   update_cache: True
  tags:
    - install
    - latex

- name: TeXStudio Fix Keyring
  become: true
  shell: >
    apt-key export 7C387DD3 | gpg --dearmor -o /etc/apt/trusted.gpg.d/texstudio.gpg
    && apt-key --keyring /etc/apt/trusted.gpg del 7C387DD3
  tags:
    - install
    - productivity

- name: Install TeXstudio
  become: true
  apt:
    update_cache: yes
    name: [
      "texstudio"
    ]
  tags:
    - install
    - latex

- name: Install LaTeX Dependencies
  become: true
  apt:
    update_cache: yes
    name: [
      "asymptote",
      "asymptote-doc",
      "ghostscript",
      "ghostscript-x",
      "biber",
      "dvipng",
      "latexdiff",
      "latexmk",
      "okular"
    ]
  tags:
    - install
    - latex

- name: Install Giant TexLive metapackage
  become: true
  apt:
    update_cache: yes
    name: [
      "texlive-full"
    ]
  tags:
    - install
    - latex

