- name: Install LaTeX Dependencies
  become: true
  apt:
    update_cache: yes
    name: [
      "texlive-full",
      "asymptote",
      "asymptote-doc",
      "ghostscript",
      "ghostscript-x",
      "biber",
      "dvipng",
      "latexdiff",
      "latexmk",
      "okular"
    ]
  tags:
    - install
    - latex

- name: Download TeXstudio .deb
  get_url:
    url: http://downloadcontent.opensuse.org/repositories/home:/jsundermeyer/xUbuntu_20.04/amd64/texstudio_4.1.1-1+1.1_amd64.deb
    dest: /tmp/texstudio.deb
  tags:
    - install
    - latex

- name: Install TeXstudio .deb package
  become: true
  apt:
    deb: /tmp/texstudio.deb
  tags:
    - install
    - latex
