- name: TeXstudio PPA (ppa:sunderme/texstudio)
  become: true
  apt_repository:
   repo: ppa:sunderme/texstudio
   state: present
   update_cache: True
  tags:
    - install
    - latex

- name: Install TeXstudio
  become: true
  apt:
    update_cache: yes
    name: [
      "texstudio"
    ]
  tags:
    - install
    - latex

- name: Install LaTeX Dependencies
  become: true
  apt:
    update_cache: yes
    name: [
      "asymptote",
      "asymptote-doc",
      "ghostscript",
      "ghostscript-x",
      "biber",
      "dvipng",
      "latexdiff",
      "latexmk",
      "okular"
    ]
  tags:
    - install
    - latex

- name: Install Giant TexLive metapackage
  become: true
  apt:
    update_cache: yes
    name: [
      "texlive-full"
    ]
  tags:
    - install
    - latex

