- name: microsoft | Download .NET .deb
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/config/ubuntu/{{ buntu_ver }}/packages-microsoft-prod.deb
    dest: /tmp/microsoft.deb
  tags:
    - install
    - dotnet

- name: microsoft | Install .NET .deb package
  become: true
  ansible.builtin.apt:
    deb: /tmp/microsoft.deb
  tags:
    - install
    - dotnet

- name: microsoft | Download Visual Studio Code .deb
  ansible.builtin.get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    dest: /tmp/code.deb
  tags:
    - install
    - ide
    - vscode

- name: microsoft | Install Visual Studio Code .deb package
  become: true
  ansible.builtin.apt:
    deb: /tmp/code.deb
  tags:
    - install
    - ide
    - vscode

- name: microsoft | Install Microsoft Packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: ["dotnet-sdk-8.0", "powershell"]
  tags:
    - install
    - browser
    - dotnet

- name: microsoft | Install .NET tools
  ansible.builtin.shell: >
    dotnet tool install -g dotnet-ef
    && dotnet tool install -g dotnet-aspnet-codegenerator
  tags:
    - install
    - dotnet
