---
- name: php | Install base packages
  become: true
  ansible.builtin.apt:
    name: [
      "php",
      "php-cli",
      "php-mbstring",
      "php-curl",
      "php-xml"
    ]
    state: latest
  tags:
    - install
    - php

- name: php | Download composer install
  become: true
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
  tags:
    - install
    - php

- name: php | Install composer
  become: true
  ansible.builtin.shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  tags:
    - install
    - php
