---
- name: productivity | Add wezterm repository
  become: true
  ansible.builtin.shell: >
    curl -fsSL https://apt.fury.io/wez/gpg.key | gpg --yes --dearmor -o /etc/apt/trusted.gpg.d/wezterm-fury.gpg
    && chmod a+r /etc/apt/trusted.gpg.d/wezterm-fury.gpg
    && echo "deb [signed-by=/etc/apt/trusted.gpg.d/wezterm-fury.gpg] https://apt.fury.io/wez/ * *" | tee /etc/apt/sources.list.d/wezterm.list > /dev/null
  tags:
    - install
    - tty
    - productivity

- name: productivity | Clone my wezterm config
  ansible.builtin.git:
    repo: 'https://github.com/code-chimp/wezterm-config.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/wezterm"
  tags:
    - install
    - tty
    - productivity
    - dotfiles

- name: productivity | Download Dropbox .deb
  ansible.builtin.get_url:
    url: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_{{ dropbox_ver }}_amd64.deb
    dest: /tmp/dropbox.deb
  tags:
    - install
    - productivity

- name: productivity | Install Dropbox .deb package
  become: true
  ansible.builtin.apt:
    deb: /tmp/dropbox.deb
  tags:
    - install
    - productivity

- name: productivity | KeepassXC PPA (ppa:phoerious/keepassxc)
  become: true
  ansible.builtin.shell: apt-add-repository -y ppa:phoerious/keepassxc
  tags:
    - install
    - productivity

- name: productivity | GIMP PPA (ppa:ubuntuhandbook1/gimp)
  become: true
  ansible.builtin.shell: apt-add-repository -y ppa:ubuntuhandbook1/gimp
  tags:
    - install
    - productivity

- name: productivity | Inkscape PPA (ppa:inkscape.dev/stable)
  become: true
  ansible.builtin.shell: apt-add-repository -y ppa:inkscape.dev/stable
  tags:
    - install
    - productivity

- name: productivity | Install Random Productivity Tools
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: [
      "bc",
      "wireshark",
      "xclip",
      "tldr",
      "ripgrep",
      "shutter",
      "k3b",
      "k3b-data",
      "k3b-extrathemes",
      "gimp",
      "gimp-data",
      "gimp-data-extras",
      "gimp-gmic",
      "gimp-gutenprint",
      "inkscape",
      "keepassxc",
      "dropbox",
      "skanlite",
      "wezterm"
    ]
  tags:
    - install
    - productivity
