- name: slack | Download Slack
  ansible.builtin.get_url:
    url: https://downloads.slack-edge.com/releases/linux/{{ slack_ver }}/prod/x64/slack-desktop-{{ slack_ver }}-amd64.deb
    dest: /tmp/slack.deb
  tags:
    - install
    - slack

- name: slack | Remove Any previous slacks
  become: true
  ansible.builtin.apt:
    name: slack-desktop
    state: absent
  tags:
    - install
    - slack

- name: slack | Install Slack .deb package
  become: true
  ansible.builtin.apt:
    deb: /tmp/slack.deb
  tags:
    - install
    - slack
