- name: Download Slack
  get_url:
    url: https://downloads.slack-edge.com/releases/linux/{{ slackver }}/prod/x64/slack-desktop-{{ slackver }}-amd64.deb
    dest: /tmp/slack.deb
  tags:
    - install
    - slack

- name: Remove Any previous slacks
  become: true
  apt:
    name: slack-desktop
    state: absent
  tags:
    - install
    - slack

- name: Install Slack .deb package
  become: true
  apt:
    deb: /tmp/slack.deb
  tags:
    - install
    - slack

